reload("user.plugins")
reload("user.colorscheme")
reload("user.options")
reload("user.keymaps")
reload("user.which-key")
reload("user.statusline")
reload("user.lsp")
reload("user.dashboard")
-- require("lvim.lsp.manager").setup("angularls")
-- reload('user.lsp-status')
reload("user.autocmds")
